FROM python:3.11



COPY . /home/onnet_cabinet

WORKDIR /home/onnet_cabinet

RUN pip install -r requirements.txt

WORKDIR /home/onnet_cabinet/app
# EXPOSE 8001
# CMD ["fastapi", "run", "--host", "0.0.0.0", "--port", "8001"]
